publish_mode: editorial_workflow

# Uncomment the following line to use the local backend | Used with `npx decap-server`
local_backend: true

backend:
  name: git-gateway
  branch: main
  squash_merges: true
  commit_messages:
    create: "feat: create {{collection}} '{{slug}}' by {{author-name}}"
    update: "fix: update {{collection}} '{{slug}}' by {{author-name}}"
    delete: "chore: delete {{collection}} '{{slug}}' by {{author-name}}"
    uploadMedia: "feat: upload '{{path}}' by {{author-name}}"
    deleteMedia: "chore: delete '{{path}}' by {{author-name}}"
    openAuthoring: "{{message}}"

site_url: "https://culture-cupper.netlify.app/"
logo_url: https://zu.com/android-chrome-512x512.png
media_folder: "src/assets/images"

collections:
  - label: "Teams"
    name: "teams"
    label_singular: "Team"
    description: "Team"
    delete: false
    folder: "src/content/teams"
    create: true
    identifier_field: name
    preview_path: "teams/{{slug}}"
    sortable_fields: ["name"]
    editor:
      preview: false
    view_filters:
      - label: "Has Href"
        field: "href"
        pattern: ""
      - label: "Published"
        field: "published"
        pattern: true
      - label: "Unpublished"
        field: "published"
        pattern: false
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
        hint: "The name of the team"
      - label: "Members"
        name: "members"
        widget: "relation"
        collection: "members"
        search_fields: ["name"]
        value_field: "{{slug}}"
        display_fields: ["name"]
        multiple: true
        required: true
        hint: "Select team members from the members collection"
      - label: "Manual Good Points"
        name: "manualGoodPoints"
        widget: "number"
        default: 0
        value_type: "int"
        min: 0
        max: 1000
        step: 1
        required: true
        hint: "Manual adjustment to good points (added to points from games and events)"
      - label: "Manual Bad Points"
        name: "manualBadPoints"
        widget: "number"
        default: 0
        value_type: "int"
        min: 0
        max: 1000
        step: 1
        required: true
        hint: "Manual adjustment to bad points (added to points from games and events)"

  - label: "Members"
    name: "members"
    label_singular: "Member"
    description: "Member of a team"
    delete: false
    folder: "src/content/members"
    create: true
    identifier_field: name
    preview_path: "members/{{slug}}"
    sortable_fields: ["name"]
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
        hint: "The name of the member"
      - label: "Position"
        name: "position"
        widget: "string"
        required: true
        hint: "The member's position or role"
      - label: "Image"
        name: "image"
        widget: "string"
        required: true
        hint: "The team member's image path"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
        hint: "Description of the team member"
      - label: "Is Leadership"
        name: "isLeadership"
        widget: "boolean"
        default: false
        required: false
        hint: "Whether this member is part of leadership"
      - label: "Order"
        name: "order"
        widget: "number"
        default: 99
        value_type: "int"
        min: 1
        max: 999
        step: 1
        required: false
        hint: "Sorting order for display"

  - label: "Tournaments"
    name: "tournaments"
    label_singular: "Tournament"
    description: "Tournament brackets for member competitions"
    delete: false
    folder: "src/content/tournaments"
    create: true
    identifier_field: name
    preview_path: "tournaments/{{slug}}"
    sortable_fields: ["date"]
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
        hint: "The name of the tournament"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
        hint: "Description of the tournament"
      - label: "Date"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: false
        format: "YYYY-MM-DD"
        required: false
        hint: "The date of the tournament"
      - label: "Winner"
        name: "winner"
        widget: "relation"
        collection: "members"
        search_fields: ["name"]
        value_field: "{{slug}}"
        display_fields: ["name"]
        required: false
        hint: "The tournament winner"
      - label: "Show on Homepage"
        name: "showOnHomepage"
        widget: "boolean"
        default: true
        required: false
        hint: "Whether to show this tournament on the homepage"
      - label: "Matches"
        name: "matches"
        widget: "list"
        summary: "Round {{fields.round}} - Match {{fields.id}}"
        hint: "Tournament matches"
        fields:
          - label: "Match ID"
            name: "id"
            widget: "string"
            required: true
            hint: "Unique identifier for the match"
          - label: "Round"
            name: "round"
            widget: "number"
            default: 1
            value_type: "int"
            min: 1
            max: 3
            step: 1
            required: true
            hint: "Tournament round (1: first round, 2: semifinals, 3: finals)"
          - label: "Participants"
            name: "participants"
            widget: "list"
            summary: "{{fields.member}} ({{fields.isWinner}})"
            hint: "Match participants (max 2)"
            max: 2
            fields:
              - label: "Member"
                name: "member"
                widget: "relation"
                collection: "members"
                search_fields: ["name"]
                value_field: "{{slug}}"
                display_fields: ["name"]
                required: true
                hint: "Select participant from members"
              - label: "Is Winner"
                name: "isWinner"
                widget: "boolean"
                default: false
                required: true
                hint: "Whether this participant won the match"

  - label: "Events"
    name: "events"
    label_singular: "Event"
    description: "Event with team member participants and point logs"
    delete: false
    folder: "src/content/events"
    create: true
    identifier_field: name
    preview_path: "events/{{slug}}"
    sortable_fields: ["date"]
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
        hint: "The name of the event"
      - label: "Date"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: false
        format: "YYYY-MM-DD"
        required: true
        hint: "The date of the event"
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
        hint: "Description of the event"
      - label: "Participants"
        name: "participants"
        widget: "relation"
        collection: "members"
        search_fields: ["name"]
        value_field: "{{slug}}"
        display_fields: ["name"]
        multiple: true
        required: true
        hint: "Select event participants from the members collection"
      - label: "Points Logs"
        name: "pointsLogs"
        widget: "list"
        summary: "{{fields.team}} - {{fields.points}} points ({{fields.isGoodPoints}})"
        required: false
        hint: "Points awarded or deducted during this event"
        fields:
          - label: "Points"
            name: "points"
            widget: "number"
            default: 0
            value_type: "int"
            min: 0
            max: 1000
            step: 1
            required: true
            hint: "The number of points to add or subtract"
          - label: "Reason"
            name: "reason"
            widget: "string"
            required: true
            hint: "The reason for the points"
          - label: "Team"
            name: "team"
            widget: "relation"
            collection: "teams"
            search_fields: ["name"]
            value_field: "{{slug}}"
            display_fields: ["name"]
            required: true
            hint: "Select the team that gets these points"
          - label: "Is Good Points"
            name: "isGoodPoints"
            widget: "boolean"
            default: true
            required: true
            hint: "Whether these are good points (true) or bad points (false)"

  - label: "Games"
    name: "games"
    label_singular: "Game"
    description: "Game competition between teams"
    delete: false
    folder: "src/content/games"
    create: true
    identifier_field: name
    preview_path: "games/{{slug}}"
    sortable_fields: ["date"]
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
        hint: "The name of the game"
      - label: "Description"
        name: "description"
        widget: "text"
        required: true
        hint: "Description of the game"
      - label: "Date"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: false
        format: "YYYY-MM-DD"
        required: false
        hint: "The date of the game"
      - label: "Winner"
        name: "winner"
        widget: "string"
        required: false
        hint: "The winning team's name"
      - label: "Participants"
        name: "participants"
        widget: "relation"
        collection: "teams"
        search_fields: ["name"]
        value_field: "{{slug}}"
        display_fields: ["name"]
        multiple: true
        required: false
        hint: "Select participating teams"
      - label: "Points"
        name: "points"
        widget: "number"
        default: 0
        value_type: "int"
        min: 0
        max: 1000
        step: 1
        required: false
        hint: "Points awarded to the winner"

  - label: "Points Log"
    name: "points_log"
    label_singular: "Points Log"
    description: "Legacy points logging system"
    delete: false
    folder: "src/content/points-log"
    create: true
    identifier_field: "{{slug}}"
    preview_path: "points-log/{{slug}}"
    sortable_fields: ["date"]
    fields:
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
        required: true
        hint: "The date of the points log"
      - label: "Team"
        name: "team"
        widget: "relation"
        collection: "teams"
        search_fields: ["name"]
        value_field: "name"
        display_fields: ["name"]
        required: true
        hint: "Select the team from the teams collection"
      - label: "Member"
        name: "member"
        widget: "relation"
        collection: "members"
        search_fields: ["name"]
        value_field: "{{slug}}"
        display_fields: ["name"]
        required: false
        hint: "Select the member from the members collection"
      - label: "Points"
        name: "points"
        widget: "number"
        default: 0
        value_type: "int"
        min: -50
        max: 1000
        step: 1
        required: true
        hint: "The points to add or subtract"
      - label: "Reason"
        name: "reason"
        widget: "string"
        required: true
        hint: "The reason for the points log"
      - label: "Is Good Points"
        name: "isGoodPoints"
        widget: "boolean"
        default: true
        required: true
        hint: "Whether these are good points (true) or bad points (false)"
