publish_mode: editorial_workflow

# Uncomment the following line to use the local backend | Used with `npx decap-server`
# local_backend: true

backend:
  name: git-gateway
  branch: main
  squash_merges: true
  commit_messages:
    create: "feat: create {{collection}} '{{slug}}' by {{author-name}}"
    update: "fix: update {{collection}} '{{slug}}' by {{author-name}}"
    delete: "chore: delete {{collection}} '{{slug}}' by {{author-name}}"
    uploadMedia: "feat: upload '{{path}}' by {{author-name}}"
    deleteMedia: "chore: delete '{{path}}' by {{author-name}}"
    openAuthoring: "{{message}}"

site_url: "https://culture-cupper.netlify.app/"
logo_url: https://zu.com/android-chrome-512x512.png
media_folder: "src/assets/images"

collections:
  - name: "teams"
    label: "Teams"
    label_singular: "Team"
    description: "Team"
    delete: false
    folder: "src/content/teams"
    create: true
    preview_path: "teams/{{slug}}"
    sortable_fields: ["name"]
    editor:
      preview: false
    view_filters:
      - label: "Has Href"
        field: "href"
        pattern: ""
      - label: "Published"
        field: "published"
        pattern: true
      - label: "Unpublished"
        field: "published"
        pattern: false
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
        hint: "The name of the team"
      - label: "Members"
        name: "members"
        widget: "relation"
        collection: "members"
        search_fields: ["name"]
        value_field: "{{slug}}"
        display_fields: ["name"]
        multiple: true
        required: true
        hint: "Select team members from the members collection"
      - label: "Points"
        name: "points"
        widget: "number"
        default: 0
        value_type: "int"
        min: -50
        max: 1000
        step: 1

  - name: "members"
    label: "Members"
    label_singular: "Member"
    description: "Member of a team"
    delete: false
    folder: "src/content/members"
    create: true
    preview_path: "members/{{slug}}"
    sortable_fields: ["name"]
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true
        hint: "The name of the member"
      - label: "Image"
        name: "image"
        widget: "string"
        required: true
        hint: "The team members image path"
